### PR TITLE
Use fully qualified names in Authority records

### PR DESCRIPTION
**Pull request by descent3me**
**What this PR does / why we need it**:
Used fully qualified names in Authority records as is expected by the Gordon core event consumer https://github.com/spotify/gordon-gcp/blob/develop/src/gordon_gcp/schema/schemas/event.schema.json#L27

**Which issue(s) this PR fixes**

Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by descent3me** [comment]
@spotify/alf

**Comment by descent3me** [comment]
@spotify/alf Ping! It's a pretty small change to make sure we're using the defined API correctly.

**Comment by smstone** [comment]
+1

**Comment by descent3me** [comment]
Thanks!

**Pull request merged**
